#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "digidrive"
name = "Digidrive"
description.en = "Publishing content created with La Digitale tools"
description.fr = "Gérer les contenus créés avec les outils de La Digitale"

version = "0.7.5~ynh1"

maintainers = ["otm33GH"]

[upstream]
license = "AGPL-3.0-only"
website = "https://ladigitale.dev/"
demo = "https://ladigitale.dev/digidrive/#/"
admindoc = "https://codeberg.org/ladigitale/digidrive#readme"
userdoc = "https://ladigitale.dev/blog/digidrive-pour-creer-et-gerer-les-contenus-generes-sur-la-digitale"
code = "https://codeberg.org/ladigitale/digidrive"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/digidrive"
    
    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.max_upload_size]
      ask.fr = "Taille limite pour le téléchargement des fichiers en Mo"
      ask.en = "Size limit file upload (Mb)"
      type = "number"
      min = 0
      max = 5000
      help.fr = "Valeur maximale de 5Go"
      help.en = "Max size 5Gb"
      default = 200

[resources]
    [resources.sources.main]
    url = "https://codeberg.org/ladigitale/digidrive/archive/0.7.5.tar.gz"
    sha256 = "d07af0d09b530449d0fd465b19508796be91033e3f9ba1b5198db58982cc8da8"
    autoupdate.strategy = "latest_forgejo_release"

    [resources.system_user]
	allow_email = true

    [resources.install_dir]
    group = "www-data:r-x"

    [install.password]
    ask.en = "Please chose a password for the admin user."
    ask.fr = "Choisissez un mot de passe pour l'administrateur."
    type = "password"


    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "php8.5-fpm php8.5-sqlite3 php8.5-curl php8.5-xml"

    [resources.nodejs]
    version = "24"

    [resources.composer]
    version = "2.9.3"
